spring.application.name=Nhom2_OrderService
server.port=8083
spring.datasource.url=jdbc:mariadb://localhost:3306/order_db?createDatabaseIfNotExist=true
spring.datasource.driver-className=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=25082004
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/auth/.well-known/jwks.json
spring.jpa.show-sql=true
app.services.food-service.url=http://localhost:8082